name: ivan
description: Aplikasi CRUD Flutter Lengkap untuk UTS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3
  path: ^1.9.0

  shared_preferences: ^2.2.2
  curved_navigation_bar: ^1.0.3
  intl: ^0.19.0 # Untuk format tanggal & mata uang
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
